### PR TITLE
one source of truth for ~/.sami2py

### PR DESCRIPTION
**Pull request by scivision**
In regulatory / compliance bound environments, messing with sys.prefix is not allowed. Many packages (Python and otherwise) install under ~/.my_pkg_name instead of sys.prefix in any case. This PR follows that convention.

Also, makes one source of truth (well almost,`setup.py` and `__init__.py`) for this directory.
Also a bit of PEP8 / namespace cleanup.

We have been working off a fork that combines this PR + #72 + #73 to make sami2py usable in general.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by JonathonMSmith** [comment]
Maybe this PR isn't the place for this discussion, but with these changes, if there are multiple installations of sami2py in several VMs then they will all share the ~/.sami2py contents. The use of sys.prefix was added so that virtual machines would always have their own ".sami2py". Clearly, this breaks for regulatory / compliance bound environments so it must be removed. Perhaps there's another solution to this or it's not considered an issue at all and the contents should just be changed manually when switching between environments.

**Comment by scivision** [comment]
OK I wondered about that for venv as a motivator. Possibilities include:

* make this .sami2py location user-selectable at install (I can't even install sami2py with sys.prefix/.sami2py)
* make the .sami2py location under ~/.sami2py/<venv name>

**Comment by jklenzing** [comment]
I think I've sorted out the merge conflicts and kept the intent of this PR.  Let me know if something looks off.

As for the venv issues, I like the second option.  Not sure if we should try to address that here or in a separate PR.  @JonathonMSmith?

**Comment by scivision** [comment]
208b912 fixes a couple typos from the rebase on develop

**Comment by JonathonMSmith** [comment]
I'm happy with leaving the venv for another issue/PR

**Comment by scivision** [comment]
Yea in essence this allows anyone that doesn't have sudo/admin access, or even the ability to modify the directories under the Python install, to install sami2py.

**Comment by jklenzing** [comment]
OK.  Writing this up as a new issue.

**Pull request merged**
